enableFeaturePreview("TYPESAFE_PROJECT_ACCESSORS")

rootProject.name = "Sonus"

include("protocol")
include("service")
include("agent-paper")
include("svc-protocol")
include("svc-adapter")
include("plasmo-protocol")
include("plasmo-adapter")
include("web-protocol")
include("web-adapter")
include("webrtc-pion")
include("webrtc-adapter")
include("webrtc-ipc")
include("common")
include("common-protocol")
include("service-velocity")
include("network")
